apiVersion: batch/v1
kind: Job
metadata:
  name: mtls-client
spec:
  completions: 5
  parallelism: 10
  template:
    spec:
      containers:
      - name: mtls-client
        image: ./mtls-client
      restartPolicy: Never
  backoffLimit: 4